# Generated by Django 4.0.5 on 2022-06-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=20, verbose_name='지원자')),
                ('recruiter', models.CharField(max_length=20, verbose_name='채용자')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(default='user', max_length=20, verbose_name='사용자 타입'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='usertype',
            name='useremail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
