# Generated by Django 4.0.5 on 2022-06-17 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usertype_usermodel_user_type_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(verbose_name='지원일')),
                ('login_date', models.DateTimeField(verbose_name='로그인일')),
                ('logout_date', models.DateTimeField(verbose_name='로그아웃일')),
                ('useremail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
